[project]
name = "telenotes"
version = "0.1.0"
description = "Notes for telegram."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "python-dotenv>=1.1.1",
    "python-telegram-bot>=22.3",
]
